### ISSUE TITLE
Add support for deriving the 'Uniforms' trait

### ISSUE THREAD

**Issue by zesterer** [glium/glium_derive#2]
Example:

```rust
#[derive(Uniforms)]
struct MyUniforms {
    #[glium(attr = "matrix")
    matrix: [f32; 16],
}
```

**Comment by voidxnull** [comment]
I'm sorry for the delay, I didn't have my notifications set up properly.
Unfortunately, I don't use glium in my projects anymore so I'm transferring the repo to the glium organisation. However, I'll accept the PR if you implement it.

**Comment by Boscop** [comment]
@zesterer You mean as replacement for `implement_uniform_block`, right? 
I'm also interested in this. 
@voidxnull Would you still accept a PR? :)

**Comment by voidxnull** [comment]
@Boscop Yeah, of course.

**Comment by nikarh** [comment]
I guess this can be closed now?

**Comment by est31** [comment]
Closing as per #6. Thanks @nikarh !
