### ISSUE TITLE
Undefined behavior in vertex macro

### ISSUE THREAD

**Issue by halvnykterist** [glium/glium_derive#3]
https://github.com/glium/glium_derive/blob/e79e4c3d96601cfacca745c51376bc68644855b3/src/lib.rs#L115

Because of this the compiler warns about UB when using the macro on simple vertex types like in the example, although unreliably.

**Comment by est31** [comment]
Upstream glium had this problem as well (https://github.com/glium/glium/issues/1775). I guess one has to update the code in a similar fashion to the PRs mentioned in that issue.

**Comment by voidxnull** [comment]
Should be fixed as of v0.1.4. I don't think there is a safer way to calculate the offset of a field currently. @est31 what do you think?

**Comment by est31** [comment]
@voidxnull I was recommended to use the memoffset crate by one of the experts on the topic so that's what I did in glium: https://github.com/glium/glium/issues/1775#issuecomment-522209848
